### ISSUE TITLE
Could you please provide problem name or submission status ?

### ISSUE THREAD

**Issue by zzhzz** [alexeygrigorev/codeforces-crawler#1]
I download the dataset you crawled on the kaggle, but I can't find problem name in it. Could you please provide problem name ? Thanks a lot.

**Comment by alexeygrigorev** [comment]
The problem name is also scraped and stored in mysql, but I didn't export it when saving to json. If you run the scraper yourself, you should be able to do it. It's stored in the "problem" column.

Unfortunately I cannot regenerate the dataset on kaggle as I don't have the data now.

**Comment by alexeygrigorev** [comment]
This piece of code needs modification if you want to export the problem name as well: https://github.com/alexeygrigorev/codeforces-crawler/blob/master/src/main/java/codeforcescrawl/BowFeatureExtractor.java#L50

Pull requests are welcome

**Comment by zzhzz** [comment]
I've found the mysql script in an article, which is now stored in yandex disk. https://yadi.sk/d/9yGx3a2XmWUDu

**Comment by zzhzz** [comment]
Thanks a lot.

**Comment by zzhzz** [comment]
article as follows : https://www.itshared.org/2015/12/codeforces-submissions-dataset-for.html
